// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvfiu23PioPsz5uHAFCJ1tyjznSvMhFqk',
    appId: '1:721944977602:web:25186497c3f6d34d1f5b5b',
    messagingSenderId: '721944977602',
    projectId: 'navomesh-85b83',
    authDomain: 'navomesh-85b83.firebaseapp.com',
    storageBucket: 'navomesh-85b83.firebasestorage.app',
    measurementId: 'G-RC8L8L1B54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4f1CiDKBAq8oTPPyto1UIZKH3sVl8VvQ',
    appId: '1:721944977602:android:9066439c363d30fa1f5b5b',
    messagingSenderId: '721944977602',
    projectId: 'navomesh-85b83',
    storageBucket: 'navomesh-85b83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOCFB7MYopp8Jtie_I9Cu3DnayrkkA0Cg',
    appId: '1:721944977602:ios:805a90ea3396420b1f5b5b',
    messagingSenderId: '721944977602',
    projectId: 'navomesh-85b83',
    storageBucket: 'navomesh-85b83.firebasestorage.app',
    iosBundleId: 'com.example.commuteiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOCFB7MYopp8Jtie_I9Cu3DnayrkkA0Cg',
    appId: '1:721944977602:ios:805a90ea3396420b1f5b5b',
    messagingSenderId: '721944977602',
    projectId: 'navomesh-85b83',
    storageBucket: 'navomesh-85b83.firebasestorage.app',
    iosBundleId: 'com.example.commuteiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvfiu23PioPsz5uHAFCJ1tyjznSvMhFqk',
    appId: '1:721944977602:web:7ddf4d20700843451f5b5b',
    messagingSenderId: '721944977602',
    projectId: 'navomesh-85b83',
    authDomain: 'navomesh-85b83.firebaseapp.com',
    storageBucket: 'navomesh-85b83.firebasestorage.app',
    measurementId: 'G-NBQWK03CWJ',
  );
}
